### ISSUE TITLE
你太好骗了

### ISSUE THREAD

**Issue by ksqeib445** [KagurazakaSarah/dalaos--saying#1]
![JROLP~T0M1Q2`STV3`G`M}D mirai](https://user-images.githubusercontent.com/28245341/104806148-3a8d6c80-5810-11eb-9a1a-ff8ee47b8d48.jpg)
你真以为
我会说什么
？
涩图而已

**Comment by ksqeib445** [comment]
你又被骗了 哈哈哈哈

**Comment by KagurazakaSarah** [comment]
我为什么要上当呢，智障而已。@icebear67__同上
